
import "./globals.css";
import Hero from "./components/Hero";
import Header from "./components/Header";
import Roadmap from "./components/Roadmap";

import "@fontsource/gowun-dodum";
import "@fontsource/londrina-solid";
import "@fontsource/londrina-shadow";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body className="bg-ber-yellow text-gray-800">
        <Header />
        <Hero />
        <Roadmap />
      </body>

    </html>
  );
}
