
import "./globals.css";
import Hero from "./components/Hero";
import Header from "./components/Header";
import Roadmap from "./components/Roadmap";
import Gif from "./components/Gif";
import About from "./components/About";

import "@fontsource/gowun-dodum";
import "@fontsource/londrina-solid";
import "@fontsource/londrina-shadow";
import Tokenomics from "./components/Tokenomics";
import Community from "./components/Community";
import BearDivider from "./components/BearDivider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body className="bg-ber-yellow text-gray-800">
        <Header />
        <Hero />
        <Roadmap />
        <Gif />
        <Tokenomics />
        <About />
        <Community />
        <BearDivider />

      </body>

    </html>
  );
}
